# Generated by Django 4.1.6 on 2023-06-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_vehiculo',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vehiculo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('PatenteMoto', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('anno', models.CharField(max_length=20)),
                ('file', models.ImageField(upload_to='img/motos')),
                ('comentario', models.CharField(max_length=200)),
                ('idtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_auto.tipo_vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('PatenteAuto', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('anno', models.CharField(max_length=20)),
                ('file', models.ImageField(upload_to='img/autos')),
                ('comentario', models.CharField(max_length=200)),
                ('idtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_auto.tipo_vehiculo')),
            ],
        ),
    ]
