# Generated by Django 4.1.6 on 2023-06-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='file',
            field=models.FileField(upload_to='img/autos'),
        ),
        migrations.AlterField(
            model_name='motocicleta',
            name='file',
            field=models.FileField(upload_to='img/motos'),
        ),
    ]
